# Generated by Django 5.0.3 on 2024-05-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_release_date_alter_movie_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='poster_path',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
