# Generated by Django 5.0.3 on 2024-05-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_person_poster_path_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='poster_path',
        ),
    ]
