# Generated by Django 5.0.3 on 2024-05-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
